import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar structure for Physical AI Book
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Chapter 1: Introduction to Physical AI',
      items: [
        'chapter-1/intro',
        'chapter-1/lesson-1',
        'chapter-1/lesson-2',
        'chapter-1/lesson-3',
      ],
    },
    {
      type: 'category',
      label: 'Chapter 2: Advanced Physical AI Concepts',
      items: [
        'chapter-2/intro',
        'chapter-2/lesson-1',
        'chapter-2/lesson-2',
        'chapter-2/lesson-3',
      ],
    },
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [
        'tutorial-basics/welcome',
      ],
    },
    'contributing',
  ],
};

export default sidebars;
